import {
  SiReact,
  SiAngular,
  SiJavascript,
  SiTypescript,
  SiExpress,
  SiFlask,
  SiPhp,
  SiNodedotjs,
  SiPython,
  SiMysql,
  SiRedis,
  SiCplusplus,
  SiMqtt,
  SiRaspberrypi,
  SiTensorflow,
  SiGooglecloud,
  SiDocker,
  SiGit,
  SiJinja,
  SiBootstrap,
  SiAndroid,
  SiOpenjdk,
} from "react-icons/si";
import { FaAws } from "react-icons/fa";
import { TbBrandReactNative } from "react-icons/tb";
import type { IconType } from "react-icons";

export const skillIcons: Record<string, IconType> = {
  React: SiReact,
  Angular: SiAngular,
  "React Native": TbBrandReactNative,
  JavaScript: SiJavascript,
  TypeScript: SiTypescript,
  "Express.js": SiExpress,
  Flask: SiFlask,
  PHP: SiPhp,
  "Node.js": SiNodedotjs,
  Python: SiPython,
  MySQL: SiMysql,
  Redis: SiRedis,
  "C/C++": SiCplusplus,
  "C++": SiCplusplus,
  MQTT: SiMqtt,
  "Raspberry Pi": SiRaspberrypi,
  TensorFlow: SiTensorflow,
  GCP: SiGooglecloud,
  AWS: FaAws,
  Docker: SiDocker,
  Git: SiGit,
  Jinja2: SiJinja,
  Bootstrap: SiBootstrap,
  Android: SiAndroid,
  Java: SiOpenjdk,
  SQL: SiMysql,
};
